security:
    encoders:
        App\Entity\User: bcrypt

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_firewall:
            pattern:  ^/admin
            security: true
            anonymous: true
            form_login:
                login_path: dom_admin_login
                check_path: dom_admin_login
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - App\Security\AdminAuthenticator
            logout:
                  path: dom_admin_logout

        main:
            anonymous: ~

    access_control:
        # but, definitely allow /login to be accessible anonymously
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # if you wanted to force EVERY URL to be protected
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
