# This file sets the configuration of the 'Product' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/DomAdminBundle
dom_api:
    design:
        menu:
            -   label: 'menu.product'
                icon: 'shopping-basket'
                children:
                    - { entity: 'Product', icon: 'th-list', label: 'menu.product.list', params: { sortField: 'createdAt' }, default: true }
                    - { entity: 'Product', icon: 'plus-circle', label: 'menu.product.add', params: { action: 'new' } }

    entities:
        Category:
            class: App\Entity\Category
            label: 'Categories'
            list:
                title: 'Product %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', label: 'Parent category' }
                    - 'products'
            show:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label', css_class: 'large' }
                    - { property: 'parent', label: 'Parent category' }
                    - 'products'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'name', label: 'Label', css_class: 'large', help: 'As displayed on the website (the slug is auto-generated)' }
                    - { property: 'parent', type: 'domadmin_autocomplete', label: 'Parent category' }
                    # if you want to add products when creating categories, add the 'by_reference' option
                    # - { property: 'products', type_options: { by_reference: false } }

        Product:
            class: App\Entity\Product
            list:
            get:
                fields:
                    - id
                    - { property: 'name' }
                    - description
                    - { property: 'enabled', label: 'Published' }
                    - createdAt
                    - price
                    - { property: 'ean', type: 'string' }
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
                    - features
                    - categories
                    - tags
            form:
                fields:
                    - { type: 'tab', label: 'Tab 1', icon: 'pencil' }
                    - { type: 'group',  label: 'Basic information', icon: 'pencil' }
                    - { property: 'name', css_class: 'large' }
                    - { property: 'description', type: 'fos_ckeditor' }
                    - { type: 'divider' }
                    - { property: 'categories', type: 'domadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-4', label: 'Product Details', icon: 'cube' }
                    - { property: 'ean', help: 'EAN-13 valid code. Leave empty if unknown.' }
                    - { property: 'price', type: 'number' }
                    - { type: 'section', label: 'Advanced Settings', icon: 'warning', help: 'Reserved for administrators use' }
                    - { property: 'enabled', label: 'Published' }
                    - { property: 'createdAt' }
                    - { type: 'tab', label: 'Tab 2', icon: 'pencil' }
                    - { type: 'group', css_class: 'col-sm-8 new-row' }
                    - { property: 'features' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'tags' }
                    - { type: 'group', css_class: 'col-sm-4', label: 'Attachments', icon: 'paperclip' }
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: true } }
