homepage:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: domadmin
        permanent: true

#backend:
#    resource: '../src/Controller/AdminController.php'
#    prefix: /admin
#    type: annotation

dom_admin_translations:
    path: /admin/translations
    defaults:
        _controller: DomAdminBundle:Admin:translations
